services:
  nginx-server:
    image: nginx:latest       # Usa a imagem oficial do Nginx
    ports:
      - "8080:80"             # Mapeia a porta 8080 do host para a porta 80 do container
    volumes:
      - ./html:/usr/share/nginx/html  # Compartilha a pasta local ./html com o container
    networks:
      - nginx-network         # Adiciona o serviço à rede especificada

networks:
  nginx-network:
    driver: bridge            # Usa o driver de rede padrão do Docker